[docs]
title = "afterpython's Documentation"
description = "CLI tool for AfterPython"
keywords = []
authors = [{name = "Stephen Yau", email = "softwareentrepreneer+afterpython@gmail.com"}]
github = "https://github.com/AfterPythonOrg/afterpython"
license = "Apache-2.0"
copyright = "Â© afterpython 2025. All rights reserved."
