# Extra information that pyproject.toml doesn't support should be stored in afterpython.toml
[company]
name = "AfterPython.Org"
url = "https://afterpython.org"

[website]
url = "https://ap.afterpython.org"
